#!/bin/bash

validate_file "$PATH_TEMPLATES_BASE_DOMAIN_COMMON_BASEENTITY"
validate_file "$PATH_TEMPLATES_BASE_DOMAIN_ENTITIES_EXAMPLE"
validate_file "$PATH_TEMPLATES_BASE_DOMAIN_ENUMS_EXAMPLEENUM"
validate_file "$PATH_TEMPLATES_BASE_DOMAIN_INTERFACES_IEXAMPLEREPOSITORY"
validate_file "$PATH_TEMPLATES_BASE_DOMAIN_INTERFACES_IBASEREPOSITORY"
validate_file "$PATH_TEMPLATES_BASE_DOMAIN_VALIDATIONS_DOMAINEXCEPTIONVALIDATION"


NEW_DOMAIN_COMMON_BASEENTITY="$PROJECT_NAME.Domain/Common/BaseEntity.cs"
NEW_DOMAIN_ENTITIES_EXAMPLE="$PROJECT_NAME.Domain/Entities/Example.cs"
NEW_DOMAIN_ENUMS_EXAMPLEENUM="$PROJECT_NAME.Domain/Enums/ExampleEnum.cs"
NEW_DOMAIN_INTERFACES_IEXAMPLEREPOSITORY="$PROJECT_NAME.Domain/Interfaces/IExampleRepository.cs"
NEW_DOMAIN_INTERFACES_IBASEREPOSITORY="$PROJECT_NAME.Domain/Interfaces/IBaseRepository.cs"
NEW_DOMAIN_VALIDATIONS_DOMAINEXCEPTIONVALIDATION="$PROJECT_NAME.Domain/Validations/DomainExceptionValidation.cs"

sed "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" "$PATH_TEMPLATES_BASE_DOMAIN_COMMON_BASEENTITY" > "$NEW_DOMAIN_COMMON_BASEENTITY"
sed "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" "$PATH_TEMPLATES_BASE_DOMAIN_ENTITIES_EXAMPLE" > "$NEW_DOMAIN_ENTITIES_EXAMPLE"
sed "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" "$PATH_TEMPLATES_BASE_DOMAIN_ENUMS_EXAMPLEENUM" > "$NEW_DOMAIN_ENUMS_EXAMPLEENUM"
sed "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" "$PATH_TEMPLATES_BASE_DOMAIN_INTERFACES_IEXAMPLEREPOSITORY" > "$NEW_DOMAIN_INTERFACES_IEXAMPLEREPOSITORY"
sed "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" "$PATH_TEMPLATES_BASE_DOMAIN_INTERFACES_IBASEREPOSITORY" > "$NEW_DOMAIN_INTERFACES_IBASEREPOSITORY"
sed "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" "$PATH_TEMPLATES_BASE_DOMAIN_VALIDATIONS_DOMAINEXCEPTIONVALIDATION" > "$NEW_DOMAIN_VALIDATIONS_DOMAINEXCEPTIONVALIDATION"

validate_file "$NEW_DOMAIN_COMMON_BASEENTITY"
validate_file "$NEW_DOMAIN_ENTITIES_EXAMPLE"
validate_file "$NEW_DOMAIN_ENUMS_EXAMPLEENUM"
validate_file "$NEW_DOMAIN_INTERFACES_IEXAMPLEREPOSITORY"
validate_file "$NEW_DOMAIN_INTERFACES_IBASEREPOSITORY"
validate_file "$NEW_DOMAIN_VALIDATIONS_DOMAINEXCEPTIONVALIDATION"

print_info "Created domain structures."
