#!/bin/bash

NEW_INFRA_DATA_CONTEXT_APPLICATIONDBCONTEXT="$SOLUTION_NAME.Infra.Data/Context/ApplicationDbContext.cs"
NEW_INFRA_DATA_ENTITIESCONFIGURATIONS_EXAMPLECONFIGURATION="$SOLUTION_NAME.Infra.Data/EntitiesConfiguration/ExampleConfiguration.cs"
NEW_INFRA_DATA_HELPERS_DATA_SEEDDATA="$SOLUTION_NAME.Infra.Data/Helpers/Data/SeedData.cs"
NEW_INFRA_DATA_REPOSITORIES_EXAMPLEREPOSITORY="$SOLUTION_NAME.Infra.Data/Repositories/ExampleRepository.cs"
NEW_INFRA_DATA_REPOSITORIES_BASEREPOSITORY="$SOLUTION_NAME.Infra.Data/Repositories/BaseRepository.cs"

sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_INFRA_DATA_CONTEXT_APPLICATIONDBCONTEXT" > "$NEW_INFRA_DATA_CONTEXT_APPLICATIONDBCONTEXT"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_INFRA_DATA_ENTITIESCONFIGURATIONS_EXAMPLECONFIGURATION" > "$NEW_INFRA_DATA_ENTITIESCONFIGURATIONS_EXAMPLECONFIGURATION"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_INFRA_DATA_HELPERS_DATA_SEEDDATA" > "$NEW_INFRA_DATA_HELPERS_DATA_SEEDDATA"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_INFRA_DATA_REPOSITORIES_EXAMPLEREPOSITORY" > "$NEW_INFRA_DATA_REPOSITORIES_EXAMPLEREPOSITORY"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_INFRA_DATA_REPOSITORIES_BASEREPOSITORY" > "$NEW_INFRA_DATA_REPOSITORIES_BASEREPOSITORY"

validate_file "$NEW_INFRA_DATA_CONTEXT_APPLICATIONDBCONTEXT"
validate_file "$NEW_INFRA_DATA_ENTITIESCONFIGURATIONS_EXAMPLECONFIGURATION"
validate_file "$NEW_INFRA_DATA_HELPERS_DATA_SEEDDATA"
validate_file "$NEW_INFRA_DATA_REPOSITORIES_EXAMPLEREPOSITORY"
validate_file "$NEW_INFRA_DATA_REPOSITORIES_BASEREPOSITORY"

print_info "Created infrastructure data structures."


# Change PrivateAssets to none in Microsoft.EntityFrameworkCore.Design
PATH_INFRA_DATA_CSPROJ="$SOLUTION_NAME.Infra.Data/$SOLUTION_NAME.Infra.Data.csproj"
sed -i '/Microsoft.EntityFrameworkCore.Design/,/PackageReference>/{
    /PrivateAssets/s/all/none/
}' $PATH_INFRA_DATA_CSPROJ
