#!/bin/bash
NEW_API_APPSETTINGSDEVELOPMENT="$SOLUTION_NAME.Api/appsettings.Development.json"
sed -e "s/{{SOLUTION_NAME}}/$(echo "$SOLUTION_NAME" | tr '[:lower:]' '[:upper:]')/g" -e "s/{{DB_EXTERNAL_PORT}}/$DB_EXTERNAL_PORT/g" "$PATH_TEMPLATES_BASE_API_APPSETTINGSDEVELOPMENT" > "$NEW_API_APPSETTINGSDEVELOPMENT"
validate_file "$NEW_API_APPSETTINGSDEVELOPMENT"

NEW_API_DOCKERFILE="$SOLUTION_NAME.Api/Dockerfile"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_API_DOCKERFILE" > "$NEW_API_DOCKERFILE"
validate_file "$NEW_API_DOCKERFILE"

NEW_API_DOCKERFILELIVE="$SOLUTION_NAME.Api/Dockerfile.live"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_API_DOCKERFILELIVE" > "$NEW_API_DOCKERFILELIVE"
validate_file "$NEW_API_DOCKERFILELIVE"

NEW_API_PROGRAM="$SOLUTION_NAME.Api/Program.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_API_PROGRAM" > "$NEW_API_PROGRAM"
validate_file "$NEW_API_PROGRAM"

NEW_API_CONTROLLERS_SHARED_APICONTROLLERBASE="$SOLUTION_NAME.Api/Controllers/Shared/ApiControllerBase.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_API_CONTROLLERS_SHARED_APICONTROLLERBASE" > "$NEW_API_CONTROLLERS_SHARED_APICONTROLLERBASE"
validate_file "$NEW_API_CONTROLLERS_SHARED_APICONTROLLERBASE"

NEW_API_CONTROLLERS_V1_EXAMPLECONTROLLER="$SOLUTION_NAME.Api/Controllers/v1/ExampleController.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_API_CONTROLLERS_V1_EXAMPLECONTROLLER" > "$NEW_API_CONTROLLERS_V1_EXAMPLECONTROLLER"
validate_file "$NEW_API_CONTROLLERS_V1_EXAMPLECONTROLLER"

NEW_API_CONTROLLERS_V1_EXAMPLEITEMCONTROLLER="$SOLUTION_NAME.Api/Controllers/v1/ExampleItemsController.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_API_CONTROLLERS_V1_EXAMPLEITEMCONTROLLER" > "$NEW_API_CONTROLLERS_V1_EXAMPLEITEMCONTROLLER"
validate_file "$NEW_API_CONTROLLERS_V1_EXAMPLEITEMCONTROLLER"

NEW_API_EXTENSIONS_APIVERSIONINGSETUP="$SOLUTION_NAME.Api/Extensions/ApiVersioningSetup.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_API_EXTENSIONS_APIVERSIONINGSETUP" > "$NEW_API_EXTENSIONS_APIVERSIONINGSETUP"
validate_file "$NEW_API_EXTENSIONS_APIVERSIONINGSETUP"

NEW_API_EXTENSIONS_SWAGGERSETUP="$SOLUTION_NAME.Api/Extensions/SwaggerSetup.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_API_EXTENSIONS_SWAGGERSETUP" > "$NEW_API_EXTENSIONS_SWAGGERSETUP"
validate_file "$NEW_API_EXTENSIONS_SWAGGERSETUP"

NEW_API_PROPERTIES_LAUNCHSETTINGS="$SOLUTION_NAME.Api/Properties/launchSettings.json"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_API_PROPERTIES_LAUNCHSETTINGS" > "$NEW_API_PROPERTIES_LAUNCHSETTINGS"
validate_file "$NEW_API_PROPERTIES_LAUNCHSETTINGS"

print_info "Created API structures."