#!/bin/bash

NEW_DOMAIN_COMMON_BASEENTITY="$SOLUTION_NAME.Domain/Common/BaseEntity.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_DOMAIN_COMMON_BASEENTITY" > "$NEW_DOMAIN_COMMON_BASEENTITY"
validate_file "$NEW_DOMAIN_COMMON_BASEENTITY"

NEW_DOMAIN_ENTITIES_EXAMPLE="$SOLUTION_NAME.Domain/Entities/Example.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_DOMAIN_ENTITIES_EXAMPLE" > "$NEW_DOMAIN_ENTITIES_EXAMPLE"
validate_file "$NEW_DOMAIN_ENTITIES_EXAMPLE"

NEW_DOMAIN_ENTITIES_EXAMPLEITEM="$SOLUTION_NAME.Domain/Entities/ExampleItem.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_DOMAIN_ENTITIES_EXAMPLEITEM" > "$NEW_DOMAIN_ENTITIES_EXAMPLEITEM"
validate_file "$NEW_DOMAIN_ENTITIES_EXAMPLEITEM"

NEW_DOMAIN_ENUMS_EXAMPLEENUM="$SOLUTION_NAME.Domain/Enums/ExampleEnum.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_DOMAIN_ENUMS_EXAMPLEENUM" > "$NEW_DOMAIN_ENUMS_EXAMPLEENUM"
validate_file "$NEW_DOMAIN_ENUMS_EXAMPLEENUM"

NEW_DOMAIN_VALIDATIONS_DOMAINEXCEPTIONVALIDATION="$SOLUTION_NAME.Domain/Validations/DomainExceptionValidation.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_DOMAIN_VALIDATIONS_DOMAINEXCEPTIONVALIDATION" > "$NEW_DOMAIN_VALIDATIONS_DOMAINEXCEPTIONVALIDATION"
validate_file "$NEW_DOMAIN_VALIDATIONS_DOMAINEXCEPTIONVALIDATION"

NEW_DOMAIN_EXCEPTIONS_NOTFOUNDEXCEPTION="$SOLUTION_NAME.Domain/Exceptions/NotFoundException.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_DOMAIN_EXCEPTIONS_NOTFOUNDEXCEPTION" > "$NEW_DOMAIN_EXCEPTIONS_NOTFOUNDEXCEPTION"
validate_file "$NEW_DOMAIN_EXCEPTIONS_NOTFOUNDEXCEPTION"

NEW_DOMAIN_INTERFACES_IREPOSITORY="$SOLUTION_NAME.Domain/Interfaces/IRepository.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_DOMAIN_INTERFACES_IREPOSITORY" > "$NEW_DOMAIN_INTERFACES_IREPOSITORY"
validate_file "$NEW_DOMAIN_INTERFACES_IREPOSITORY"

NEW_DOMAIN_INTERFACES_IUNITOFWORK="$SOLUTION_NAME.Domain/Interfaces/IUnitOfWork.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_DOMAIN_INTERFACES_IUNITOFWORK" > "$NEW_DOMAIN_INTERFACES_IUNITOFWORK"
validate_file "$NEW_DOMAIN_INTERFACES_IUNITOFWORK"

print_info "Created domain structures."
