#!/bin/bash

NEW_INFRA_IOC_NATIVEINJECTORCONFIG="$SOLUTION_NAME.Infra.IoC/NativeInjectorConfig.cs"

sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_INFRA_IOC_NATIVEINJECTORCONFIG" > "$NEW_INFRA_IOC_NATIVEINJECTORCONFIG"

validate_file "$NEW_INFRA_IOC_NATIVEINJECTORCONFIG"

print_info "Created infrastructure IoC structures."