#!/bin/bash

NEW_INFRA_DATA_CONTEXT_APPLICATIONDBCONTEXT="$PROJECT_NAME.Infra.Data/Context/ApplicationDbContext.cs"
NEW_INFRA_DATA_ENTITIESCONFIGURATIONS_EXAMPLECONFIGURATION="$PROJECT_NAME.Infra.Data/EntitiesConfiguration/ExampleConfiguration.cs"
NEW_INFRA_DATA_HELPERS_DATA_SEEDDATA="$PROJECT_NAME.Infra.Data/Helpers/Data/SeedData.cs"
NEW_INFRA_DATA_REPOSITORIES_EXAMPLEREPOSITORY="$PROJECT_NAME.Infra.Data/Repositories/ExampleRepository.cs"
NEW_INFRA_DATA_REPOSITORIES_BASEREPOSITORY="$PROJECT_NAME.Infra.Data/Repositories/BaseRepository.cs"

sed "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" "$PATH_TEMPLATES_BASE_INFRA_DATA_CONTEXT_APPLICATIONDBCONTEXT" > "$NEW_INFRA_DATA_CONTEXT_APPLICATIONDBCONTEXT"
sed "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" "$PATH_TEMPLATES_BASE_INFRA_DATA_ENTITIESCONFIGURATIONS_EXAMPLECONFIGURATION" > "$NEW_INFRA_DATA_ENTITIESCONFIGURATIONS_EXAMPLECONFIGURATION"
sed "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" "$PATH_TEMPLATES_BASE_INFRA_DATA_HELPERS_DATA_SEEDDATA" > "$NEW_INFRA_DATA_HELPERS_DATA_SEEDDATA"
sed "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" "$PATH_TEMPLATES_BASE_INFRA_DATA_REPOSITORIES_EXAMPLEREPOSITORY" > "$NEW_INFRA_DATA_REPOSITORIES_EXAMPLEREPOSITORY"
sed "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" "$PATH_TEMPLATES_BASE_INFRA_DATA_REPOSITORIES_BASEREPOSITORY" > "$NEW_INFRA_DATA_REPOSITORIES_BASEREPOSITORY"

validate_file "$NEW_INFRA_DATA_CONTEXT_APPLICATIONDBCONTEXT"
validate_file "$NEW_INFRA_DATA_ENTITIESCONFIGURATIONS_EXAMPLECONFIGURATION"
validate_file "$NEW_INFRA_DATA_HELPERS_DATA_SEEDDATA"
validate_file "$NEW_INFRA_DATA_REPOSITORIES_EXAMPLEREPOSITORY"
validate_file "$NEW_INFRA_DATA_REPOSITORIES_BASEREPOSITORY"

print_info "Created infrastructure data structures."