#!/bin/bash

# BASE -> APPLICATION
#DTO
NEW_APPLICATION_DTO_EXAMPLE_EXAMPLEDTO="$SOLUTION_NAME.Application/DTO/Example/ExampleDTO.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_APPLICATION_DTO_EXAMPLE_EXAMPLEDTO" > "$NEW_APPLICATION_DTO_EXAMPLE_EXAMPLEDTO"
validate_file "$NEW_APPLICATION_DTO_EXAMPLE_EXAMPLEDTO"

NEW_APPLICATION_DTO_EXAMPLE_EXAMPLECREATEDTO="$SOLUTION_NAME.Application/DTO/Example/ExampleCreateDTO.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_APPLICATION_DTO_EXAMPLE_EXAMPLECREATEDTO" > "$NEW_APPLICATION_DTO_EXAMPLE_EXAMPLECREATEDTO"
validate_file "$NEW_APPLICATION_DTO_EXAMPLE_EXAMPLECREATEDTO"

NEW_APPLICATION_DTO_EXAMPLE_EXAMPLEUPDATEDTO="$SOLUTION_NAME.Application/DTO/Example/ExampleUpdateDTO.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_APPLICATION_DTO_EXAMPLE_EXAMPLEUPDATEDTO" > "$NEW_APPLICATION_DTO_EXAMPLE_EXAMPLEUPDATEDTO"
validate_file "$NEW_APPLICATION_DTO_EXAMPLE_EXAMPLEUPDATEDTO"

NEW_APPLICATION_DTO_EXAMPLEITEM_EXAMPLEITEMDTO="$SOLUTION_NAME.Application/DTO/ExampleItem/ExampleItemDTO.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_APPLICATION_DTO_EXAMPLEITEM_EXAMPLEITEMDTO" > "$NEW_APPLICATION_DTO_EXAMPLEITEM_EXAMPLEITEMDTO"
validate_file "$NEW_APPLICATION_DTO_EXAMPLEITEM_EXAMPLEITEMDTO"

NEW_APPLICATION_DTO_EXAMPLEITEM_EXAMPLEITEMCREATEDTO="$SOLUTION_NAME.Application/DTO/ExampleItem/ExampleItemCreateDTO.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_APPLICATION_DTO_EXAMPLEITEM_EXAMPLEITEMCREATEDTO" > "$NEW_APPLICATION_DTO_EXAMPLEITEM_EXAMPLEITEMCREATEDTO"
validate_file "$NEW_APPLICATION_DTO_EXAMPLEITEM_EXAMPLEITEMCREATEDTO"

NEW_APPLICATION_DTO_EXAMPLEITEM_EXAMPLEITEMUPDATEDTO="$SOLUTION_NAME.Application/DTO/ExampleItem/ExampleItemUpdateDTO.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_APPLICATION_DTO_EXAMPLEITEM_EXAMPLEITEMUPDATEDTO" > "$NEW_APPLICATION_DTO_EXAMPLEITEM_EXAMPLEITEMUPDATEDTO"
validate_file "$NEW_APPLICATION_DTO_EXAMPLEITEM_EXAMPLEITEMUPDATEDTO"

NEW_APPLICATION_DTO_SHARED_PAGEDRESULTDTO="$SOLUTION_NAME.Application/DTO/Shared/PagedResultDTO.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_APPLICATION_DTO_SHARED_PAGEDRESULTDTO" > "$NEW_APPLICATION_DTO_SHARED_PAGEDRESULTDTO"
validate_file "$NEW_APPLICATION_DTO_SHARED_PAGEDRESULTDTO"

#APPLICATION->INTERFACES
NEW_APPLICATION_INTERFACES_ISERVICEBASE="$SOLUTION_NAME.Application/Interfaces/IServiceBase.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_APPLICATION_INTERFACES_ISERVICEBASE" > "$NEW_APPLICATION_INTERFACES_ISERVICEBASE"
validate_file "$NEW_APPLICATION_INTERFACES_ISERVICEBASE"

NEW_APPLICATION_INTERFACES_IEXAMPLESERVICE="$SOLUTION_NAME.Application/Interfaces/IExampleService.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_APPLICATION_INTERFACES_IEXAMPLESERVICE" > "$NEW_APPLICATION_INTERFACES_IEXAMPLESERVICE"
validate_file "$NEW_APPLICATION_INTERFACES_IEXAMPLESERVICE"

NEW_APPLICATION_INTERFACES_IEXAMPLEITEMSERVICE="$SOLUTION_NAME.Application/Interfaces/IExampleItemService.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_APPLICATION_INTERFACES_IEXAMPLEITEMSERVICE" > "$NEW_APPLICATION_INTERFACES_IEXAMPLEITEMSERVICE"
validate_file "$NEW_APPLICATION_INTERFACES_IEXAMPLEITEMSERVICE"

#APPLICATION-MAPPINGS
NEW_APPLICATION_MAPPINGS_MAPPINGPROFILE="$SOLUTION_NAME.Application/Mappings/MappingProfile.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_APPLICATION_MAPPINGS_MAPPINGPROFILE" > "$NEW_APPLICATION_MAPPINGS_MAPPINGPROFILE"
validate_file "$NEW_APPLICATION_MAPPINGS_MAPPINGPROFILE"

NEW_APPLICATION_MAPPINGS_EXAMPLEITEMMAPPINGPROFILE="$SOLUTION_NAME.Application/Mappings/ExampleItemMappingProfile.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_APPLICATION_MAPPINGS_EXAMPLEITEMMAPPINGPROFILE" > "$NEW_APPLICATION_MAPPINGS_EXAMPLEITEMMAPPINGPROFILE"
validate_file "$NEW_APPLICATION_MAPPINGS_EXAMPLEITEMMAPPINGPROFILE"

#APPLICATION-SERVICES
NEW_APPLICATION_SERVICES_EXAMPLESERVICE="$SOLUTION_NAME.Application/Services/ExampleService.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_APPLICATION_SERVICES_EXAMPLESERVICE" > "$NEW_APPLICATION_SERVICES_EXAMPLESERVICE"
validate_file "$NEW_APPLICATION_SERVICES_EXAMPLESERVICE"

NEW_APPLICATION_SERVICES_EXAMPLEITEMSERVICE="$SOLUTION_NAME.Application/Services/ExampleItemService.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_APPLICATION_SERVICES_EXAMPLEITEMSERVICE" > "$NEW_APPLICATION_SERVICES_EXAMPLEITEMSERVICE"
validate_file "$NEW_APPLICATION_SERVICES_EXAMPLEITEMSERVICE"

NEW_APPLICATION_SERVICES_SERVICEBASE="$SOLUTION_NAME.Application/Services/ServiceBase.cs"
sed "s/{{SOLUTION_NAME}}/$SOLUTION_NAME/g" "$PATH_TEMPLATES_BASE_APPLICATION_SERVICES_SERVICEBASE" > "$NEW_APPLICATION_SERVICES_SERVICEBASE"
validate_file "$NEW_APPLICATION_SERVICES_SERVICEBASE"

print_info "Created application structures."
