version: '3.9'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db{{PROJECT_NAME}}
      POSTGRES_USER: u{{PROJECT_NAME}}
      POSTGRES_PASSWORD: p{{PROJECT_NAME}}
    ports:
      - "54321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: