version: '3.9'

services:
  webapi:
    container_name: "{{PROJECT_NAME}}.Api"
    build:
      context: .
      dockerfile: "{{PROJECT_NAME}}.Api/Dockerfile.live"
    user: 1000:1000
    ports:
      - "8000:80"
      - "9229:9229"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db{{PROJECT_NAME}}
      POSTGRES_USER: u{{PROJECT_NAME}}
      POSTGRES_PASSWORD: p{{PROJECT_NAME}}
    ports:
      - "54321:5432"
    volumes:
      - pgdata_{{PROJECT_NAME}}:/var/lib/postgresql/data

volumes:
  pgdata_{{PROJECT_NAME}}: