services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_DB_{{SOLUTION_NAME}}}
      POSTGRES_USER: ${PG_DB_{{SOLUTION_NAME}}_USER}
      POSTGRES_PASSWORD: ${PG_DB_{{SOLUTION_NAME}}_PASSWORD}
    ports:
      - "${PG_DB_{{SOLUTION_NAME}}_EXTERNAL_PORT}:5432"
    volumes:
      - pgdata_{{SOLUTION_NAME}}:/var/lib/postgresql/data

volumes:
  pgdata_{{SOLUTION_NAME}}: