services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db{{SOLUTION_NAME}}
      POSTGRES_USER: u{{SOLUTION_NAME}}
      POSTGRES_PASSWORD: p{{SOLUTION_NAME}}
    ports:
      - "54320:5432"
    volumes:
      - pgdata_{{SOLUTION_NAME}}:/var/lib/postgresql/data

volumes:
  pgdata_{{SOLUTION_NAME}}: